extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - prettier
plugins:
  - "@typescript-eslint"
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  sourceType":
    - module
  project:
    - ./tsconfig.json
rules:
  prettier/prettier:
    - error
    - semi: false
      singleQuote: true
      printWidth: 360
